### ISSUE TITLE
Error while running Skyfield tests

### ISSUE THREAD

**Issue by JoshPaterson** [brandon-rhodes/assay#12]
I am getting this traceback while trying to run the tests for skyfield. I'm using a bash shell inside of Windows Subsystem for Linux, but I'm hoping that's not causing the issue, because it doesn't seem like that would be easy to fix 😬. I reinstalled Assay from master to be certain I'm not missing any recent changes.
```
skyfield/tests/test_vectors.py line 8 in test_bad_addition
    planets = load('de421.bsp')
  skyfield/iokit.py line 182 in __call__
    return opener(path)
  skyfield/jpllib.py line 67 in __init__
    self.spk = SPK.open(path)
  /home/josh/.local/lib/python3.6/site-packages/jplephem/spk.py line 49 in open
    return cls(DAF(open(path, 'rb')))
  /home/josh/.local/lib/python3.6/site-packages/jplephem/daf.py line 62 in
  __init__
    .format(self.locidw))
ValueError: file starts with b'CI/DE421', not "NAIF/DAF" or "DAF/"
```

Thanks!

**Comment by brandon-rhodes** [comment]
Happily, that's a legitimate real test failure, nothing to do with assay. It looks like your `de421.bsp` is in the wrong format. Maybe you downloaded it from somewhere unusual? You can open the file with a hex editor (or Python) to look at more detail at those first few characters, as quoted in the error. Good luck!

**Comment by brandon-rhodes** [comment]
(Oh, and, to keep my dashboard free, I'll close this, as it looks like assay is functioning fine — but please feel free to continue the conversation here!)

**Comment by JoshPaterson** [comment]
I was able to figure out what the problem was, apparently Windows Subsytem for Linux is not able to follow the symlinks in the root `python-skyfield` folder for `de421.bsp`, `de405.bsp`, and `hip_main.dat.gz`. Replacing the symlinks with the actual files from the CI folder made all the tests run properly.

I probably should have figured that out on my own, but thanks for having a look!

**Comment by JoshPaterson** [comment]
For anyone else who might encounter this problem, I just discovered that the fix I mentioned is only necessary if you have the source code stored in your windows filesystem and are running it with python in WSL. If you move the source code to the WSL filesystem it works fine with no changes necessary.

**Comment by brandon-rhodes** [comment]
Interesting! I wonder if that’s something they’ll ever fix? Symlinks are kind of a common tool for their not to have fully supported in WSL.
